# Generated by Django 5.2 on 2025-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_jwtrefreshtoken_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtrefreshtoken',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
