# Generated by Django 5.2 on 2025-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_jwtrefreshtoken_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='refresh_token',
        ),
    ]
