  services:
    postgres:
      image: postgres 
      container_name: djstream-postgres
      environment:
        POSTGRES_DB: default
        POSTGRES_USER: kiraxd7
        POSTGRES_PASSWORD: kiraxd7
      ports:
        - "5432:5432"

    mongodb:
      image: mongo
      container_name: djstream-mongodb
      ports:
        - "27017:27017"

    rabbitmq:
      image: rabbitmq:3-management
      container_name: djstream-rabbitmq 
      ports:
        - "5672:5672"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASSWORD: guest

    redis:
      image: redis 
      container_name: djstream-redis 
      ports:
        - "6379:6379"

    auth_service:
      build:
        context: ./auth-service/
      container_name: djstream-auth-service 
      ports:
        - "8000:8000"
      environment:
        POSTGRES_NAME: default
        POSTGRES_USER: kiraxd7
        POSTGRES_PASSWORD: kiraxd7 
        POSTGRES_HOST: djstream-postgres 
        POSTGRES_PORT: 5432
        MONGO_HOST: djstream-mongodb
        MONGO_PORT: 27017
      depends_on:
        - postgres
        - mongodb 
       
    channel_service:
      build:
        context: ./channel-service/ 
      container_name: djstream-channel-service 
      ports:
        - "8001:8001"
      environment:
        POSTGRES_NAME: default
        POSTGRES_USER: kiraxd7
        POSTGRES_PASSWORD: kiraxd7 
        POSTGRES_HOST: djstream-postgres 
        POSTGRES_PORT: 5432
        RABBITMQ_HOST: djstream-rabbitmq
        RABBITMQ_PORT: 5672
      depends_on:
        - postgres
        - rabbitmq

    video_service:
      build:
        context: ./video-service/ 
      container_name: djstream-video-service 
      ports:
        - "8002:8002"
      environment:
        MONGO_HOST: djstream-mongodb
        MONGO_PORT: 27017
      depends_on:
        - mongodb 
 
    interaction_service:
      build:
        context: ./interaction-service/ 
      container_name: djstream-interaction-service 
      ports:
        - "8003:8003"
      environment:
        POSTGRES_NAME: default
        POSTGRES_USER: kiraxd7
        POSTGRES_PASSWORD: kiraxd7 
        POSTGRES_HOST: djstream-postgres 
        POSTGRES_PORT: 5432
        RABBITMQ_HOST: djstream-rabbitmq
        RABBITMQ_PORT: 5672  
      depends_on:
        - postgres
        - rabbitmq
 
    notification_service:
      build:
        context: ./notification-service/ 
      container_name: djstream-notification-service 
      ports:
        - "8004:8004"
      environment:
        AUTH_SERVICE_HOST: djstream-auth-service
        AUTH_SERVICE_PORT: 8000
        REDIS_HOST: djstream-redis
        REDIS_PORT: 6379  
        RABBITMQ_HOST: djstream-rabbitmq
        RABBITMQ_PORT: 5672
      depends_on:
        - redis
        - rabbitmq
        - auth_service

    api_gateway:
      build:
        context: ./api-gateway/ 
      container_name: djstream-api-gateway 
      ports:
        - "80:80"
      depends_on:
        - auth_service 
        - channel_service
        - video_service 
        - interaction_service
        - notification_service


    #
    #
    #

