# Generated by Django 5.2 on 2025-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
